# Generated by Django 5.1.4 on 2025-12-24 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(default='secondary', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='queueitem',
            name='status_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='queue_app.queuestatus'),
        ),
    ]
