# Generated by Django 5.1.4 on 2025-12-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_queuestatus_queueitem_status_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='status',
            field=models.CharField(default='WAITING', max_length=20),
        ),
    ]
