# Generated by Django 5.1.4 on 2025-12-24 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_alter_queueitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueitem',
            name='status',
        ),
    ]
