# Generated by Django 5.1.4 on 2025-12-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0004_remove_queueitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queueitem',
            old_name='status_fk',
            new_name='status',
        ),
    ]
