# Generated by Django 5.1.4 on 2025-12-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0006_jobsbms'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptBms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=15, unique=True)),
                ('descriptions', models.CharField(blank=True, max_length=80, null=True)),
                ('abb_desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'dept_bms',
            },
        ),
    ]
