# Generated by Django 5.1.4 on 2025-12-29 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0007_deptbms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeptBms',
        ),
        migrations.DeleteModel(
            name='JobsBms',
        ),
    ]
