# Generated by Django 5.1.4 on 2025-12-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0008_delete_deptbms_delete_jobsbms'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobno', models.IntegerField(unique=True)),
                ('catagory', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dept_tech', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee Name')),
                ('jobdate', models.DateTimeField(blank=True, null=True)),
                ('assign_date', models.DateTimeField(blank=True, null=True)),
                ('arrive_date', models.DateTimeField(blank=True, null=True)),
                ('req_date', models.DateTimeField(blank=True, null=True)),
                ('caller', models.CharField(blank=True, max_length=100, null=True)),
                ('sap_code', models.CharField(blank=True, max_length=50, null=True)),
                ('aname', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('act_dstart', models.DateTimeField(blank=True, null=True)),
                ('act_dfin', models.DateTimeField(blank=True, null=True)),
                ('job_status', models.CharField(blank=True, max_length=10, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('enterdate', models.DateTimeField(blank=True, null=True)),
                ('enterby', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('job_category_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'job_analysis_view',
                'ordering': ['-req_date'],
            },
        ),
    ]
