# Generated by Django 5.1.4 on 2025-12-29 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0009_jobanalysis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobAnalysis',
            new_name='JobsBms',
        ),
        migrations.AlterModelTable(
            name='jobsbms',
            table='jobs_bms',
        ),
    ]
