# Generated by Django 5.1.4 on 2025-12-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0010_rename_jobanalysis_jobsbms_alter_jobsbms_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsbms',
            name='abb_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobsbms',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
