# Generated by Django 5.1.4 on 2025-12-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0011_jobsbms_abb_desc_jobsbms_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='linked_job_no',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
