# Generated by Django 5.1.4 on 2025-12-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0012_queueitem_linked_job_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
