# Generated by Django 5.1.4 on 2025-12-30 00:57

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0013_queueitem_comment'),
    ]

    operations = [
        migrations.RunSQL(
            # SQL to run forwards
            [
                # QueueItem
                "ALTER TABLE queue_app_queueitem ALTER COLUMN created_at TYPE timestamp without time zone;",
                
                # JobsBms
                "ALTER TABLE jobs_bms ALTER COLUMN jobdate TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN assign_date TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN arrive_date TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN req_date TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN act_dstart TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN act_dfin TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN return_date TYPE timestamp without time zone;",
                "ALTER TABLE jobs_bms ALTER COLUMN enterdate TYPE timestamp without time zone;",
            ],
            # SQL to run backwards (restoring timezone)
            [
                "ALTER TABLE queue_app_queueitem ALTER COLUMN created_at TYPE timestamp with time zone USING created_at AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN jobdate TYPE timestamp with time zone USING jobdate AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN assign_date TYPE timestamp with time zone USING assign_date AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN arrive_date TYPE timestamp with time zone USING arrive_date AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN req_date TYPE timestamp with time zone USING req_date AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN act_dstart TYPE timestamp with time zone USING act_dstart AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN act_dfin TYPE timestamp with time zone USING act_dfin AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN return_date TYPE timestamp with time zone USING return_date AT TIME ZONE 'Asia/Bangkok';",
                "ALTER TABLE jobs_bms ALTER COLUMN enterdate TYPE timestamp with time zone USING enterdate AT TIME ZONE 'Asia/Bangkok';",
            ]
        ),
    ]
