# Generated by Django 5.1.4 on 2026-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0014_remove_timezone_from_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
