# Generated by Django 5.1.4 on 2026-01-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0015_queueitem_is_urgent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueitem',
            name='is_urgent',
            field=models.IntegerField(default=0),
        ),
    ]
