# Generated by Django 5.1.4 on 2026-01-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0016_alter_queueitem_is_urgent'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsbms',
            name='outsource_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
