# Generated by Django 5.1.4 on 2026-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0017_jobsbms_outsource_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='call_queue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
