# Generated by Django 5.1.4 on 2026-01-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0018_queueitem_call_queue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueitem',
            name='is_adhoc',
            field=models.IntegerField(default=0),
        ),
    ]
