# Generated by Django 5.1.4 on 2026-01-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0020_globalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfig',
            name='closed_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='globalconfig',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
