# Generated by Django 5.1.4 on 2026-01-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0021_globalconfig_closed_by_globalconfig_opened_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalconfig',
            old_name='updated_at',
            new_name='closed_at',
        ),
    ]
