# Generated by Django 5.1.4 on 2026-01-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0022_rename_updated_at_globalconfig_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.CharField(max_length=100, verbose_name='Closed By (Machine/IP)')),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Opened By (Machine/IP)')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
    ]
