# Generated by Django 5.1.4 on 2026-01-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0023_shiftclosure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftclosure',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
