# Generated by Django 5.1.4 on 2026-01-19 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0024_alter_shiftclosure_closed_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalConfig',
        ),
    ]
