"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# สร้าง path ภายในโปรเจค เช่น: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# คำเตือนความปลอดภัย: เก็บ secret key นี้ไว้เป็นความลับในการใช้งานจริง!
SECRET_KEY = 'django-insecure-9pu5zuv&jatunkihcs_si=^^1(k#_yg=a4(v%l#2^3h%_%15=v'

# คำเตือนความปลอดภัย: อย่าเปิด debug mode ในการใช้งานจริง (Production)!
DEBUG = True

ALLOWED_HOSTS = ['*']


# การกำหนด Application ในระบบ
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # แอปพลิเคชันของเรา
    'queue_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# ฐานข้อมูล
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# ฐานข้อมูล UAT
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'imedx_tlp_for_it',
#         'USER': 'eservices',
#         'PASSWORD': 'Tlp@2023',
#         'HOST': '192.168.98.254',
#         'PORT': '5434',
#         'OPTIONS': {
#             'options': '-c search_path=intra_tl'
#         }
#     }
# }

# ฐานข้อมูล Code7
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tlph',
        'USER': 'eservices',
        'PASSWORD': 'Tlp@2023',
        'HOST': '173.16.200.35',
        'PORT': '5435',
        'OPTIONS': {
            'options': '-c search_path=intra_tl'
        },
    }
}


# การตรวจสอบความปลอดภัยของรหัสผ่าน
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# การตั้งค่าภาษาและเขตเวลา (Internationalization)
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'th-th'

TIME_ZONE = 'Asia/Bangkok'

USE_I18N = True

USE_TZ = False


# ไฟล์ Static (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# ตำแหน่งเก็บไฟล์ Static ของโปรเจค
STATICFILES_DIRS = [
    BASE_DIR / "startbootstrap-sb-admin-2-gh-pages",
]

# สำหรับ HTTPS
# หมายเหตุ: ใน Local Development เราปิด Secure Cookies เพื่อให้ใช้งานผ่าน IP ได้สะดวก
CSRF_TRUSTED_ORIGINS = ['https://example.com', 'https://www.example.com', 'http://192.168.1.33']
SESSION_COOKIE_SECURE = False # ควรเป็น True บน Production (HTTPS)
CSRF_COOKIE_SECURE = False # ควรเป็น True บน Production (HTTPS)
SECURE_CROSS_ORIGIN_OPENER_POLICY = None # ปิดเพื่อลด Warning ใน Local Dev (IP Access)

# ประเภทของ Auto-field (Primary Key) เริ่มต้น
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
